name: fmnine
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  pinput: ^3.0.1
  molten_navigationbar_flutter: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - images/a_dot_ham.jpeg

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/static/Lora-Bold.ttf
        - asset: assets/fonts/Lora/static/Lora-BoldItalic.ttf
        - asset: assets/fonts/Lora/static/Lora-Italic.ttf
        - asset: assets/fonts/Lora/static/Lora-Medium.ttf
        - asset: assets/fonts/Lora/static/Lora-MediumItalic.ttf
        - asset: assets/fonts/Lora/static/Lora-Regular.ttf
        - asset: assets/fonts/Lora/static/Lora-SemiBold.ttf
        - asset: assets/fonts/Lora/static/Lora-SemiBoldItalic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
